### ISSUE TITLE
建议改进 Trigger interval(minutes) 

### ISSUE THREAD

**Issue by mpco** [BlackGlory/Gloria#1]
1. 增加可以输入数字时间的功能
2. 将滑动条的增长改为对数级，也就是“越靠右侧 滑动条的单位时间越大”，可以参考下 https://chrome.google.com/webstore/detail/page-monitor/ogeebjpdeabhncjpfhgdibjajcajepgg?hl=en

**Comment by BlackGlory** [comment]
@mpco 
请问一下, 你认为时间间隔的最大值为多少时是合适的?

**Comment by mpco** [comment]
我不知道，大概一两天比较合适。

**Comment by BlackGlory** [comment]
@mpco 
间隔时间有1~2天的任务为什么会需要用 Gloria? 我认为这种应用场景和 Gloria 是不适应的.

**Comment by mpco** [comment]
哦 ，对我而言，有些提醒不想实时知道，每天或者隔一两天定时出现更好。工作时不想被打扰。
我只是建议，你随意好了😂️
