### ISSUE TITLE
每次重开浏览器时，Gloria 里的任务都会执行一次。

### ISSUE THREAD

**Issue by LightAPIs** [BlackGlory/Gloria#10]
假如我创建了一个任务，间隔时间设定为 60 分钟。
在这 60 分钟内关闭再打开浏览器时，会发现任务在开启浏览器时又执行一次。也就是说这个任务并不是严格按照间隔器设定的时间进行检查的。
请问这是故意如此设计的还是我遇到了什么问题？

**Comment by BlackGlory** [comment]
Gloria的任务执行间隔是以扩展启动开始计时, 每次完全重启都会执行一次.

**Comment by LightAPIs** [comment]
原来如此。了解了。(●'◡'●)
