### ISSUE TITLE
希望可以支援繁体中文

### ISSUE THREAD

**Issue by zelda0079** [BlackGlory/Gloria#16]
套件无效，详细资料：Name of a key "appdesc​​" is invalid. Only ASCII [a-z], [A-Z], [0-9] and "_" are allowed.。

https://keylol.com/forum.php?mod=redirect&goto=findpost&ptid=581003&pid=11267001

现时只有简中和英文才能使用此插件
希望能支援繁体中文CHROME
即使显示的是英文或是简中也没关系
只是不太想改动浏览器本身语言

**Comment by BlackGlory** [comment]
[v0.13.6](https://github.com/BlackGlory/Gloria/releases/tag/v0.13.6)应能解决此问题, 由于COVID-19, Chrome应用商店的审核速度可能会慢一些.
