### ISSUE TITLE
嘤嘤嘤...能否增加窗口不要置顶...

### ISSUE THREAD

**Issue by Noah1995** [BlackGlory/Gloria#17]
1丶能否增加弹窗通知要不要置顶选项...

2丶增加一下小数字几个窗口提醒....

![【2020-04-23】【14∶07∶53】](https://user-images.githubusercontent.com/25548230/80065014-f82e4c00-856b-11ea-89de-705f6c8444b3.jpg)

**Comment by BlackGlory** [comment]
这是预定于v1.0添加的功能, 只是没时间写...

**Comment by BlackGlory** [comment]
由于 #41 关闭.
