### ISSUE TITLE
fetch function cannot transmit Cookie

### ISSUE THREAD

**Issue by Ahaochan** [BlackGlory/Gloria#19]
Hi, I try to use Gloria to listen Baidu Tieba message.
你好, 我想要使用Gloria监听百度贴吧的消息.
```js
(async () => {
    const domain = 'http://tieba.baidu.com';
    const {cheerio} = await importScripts('gloria-utils');
    const html = await fetch(domain + '/f/like/mylike?pn=1').then(res => res.text());
    const $ = cheerio.load(html);
    return { title: '1', message: '2', url: '3', iconUrl: '4'}
})().then(commit);
```
In Background Page, I can not see cookie in Request Header.
在背景页, 我在请求头里看不到cookie
![image](https://user-images.githubusercontent.com/17980786/86343749-f4b1f200-bc8b-11ea-8071-7e960be61de6.png)
But in Brower Tab, I can see cookie in Request Header.
但是在浏览器标签页, 我能在请求头看到cookie.
![image](https://user-images.githubusercontent.com/17980786/86343851-114e2a00-bc8c-11ea-87b0-6e60c2a15673.png)

Cookies are necessary to obtain private messages. what should I do?
为了获取私人消息, Cookie是必需的. 我应该怎么做呢?

Chrome Version: 81.0.4044.138
Gloria Version: 0.13.10

**Comment by BlackGlory** [comment]
Chrome其实发送了Cookie, 只是无法在DevTools中显示, Request Headers显示的信息是不完整的.

运行以下测试代码, 你可以在Background DevTools的Console面板的输出里看到你关注的贴吧:
```js
;(async () => {
    const html = await fetch('http://tieba.baidu.com/f/like/mylike?pn=1')
      .then(res => res.arrayBuffer())
      .then(buf => new TextDecoder('gbk').decode(buf))
    console.log(html)
})()
```

很抱歉没有为Gloria提供一个方便的测试环境.
