### ISSUE TITLE
能否支持 Chrome 的后台应用特性

### ISSUE THREAD

**Issue by Semidio** [BlackGlory/Gloria#2]
配合Reducer功能可以实现提醒的不间断推送

**Comment by BlackGlory** [comment]
Gloria从第一个版本开始就是在后台运行的, 提供Reducer功能的目的就是为了实现跨平台, 不存在"支持Chrome的后台应用特性"的说法.

**Comment by BlackGlory** [comment]
想了想你需要的可能是让Chrome在关闭时能够让浏览器驻留在后台, 这需要申请一个额外的权限. 目前你可以任意安装一个能让Chrome驻留的扩展程序, 这样所有其他的扩展程序也会在后台继续运行(跟开着一个空的浏览器窗口应该没有区别), 我会在下个版本里加上这个权限.

这是一个空的维持Chrome后台运行的扩展, 代码已经审查过没有问题: https://chrome.google.com/webstore/detail/background-process/gghpjpjkgffajicbeidilgkogpmianag
