### ISSUE TITLE
feature request: sync code from github

### ISSUE THREAD

**Issue by Ahaochan** [BlackGlory/Gloria#20]
I am a userscript developer and submit My code in github.
我是一个在github提交代码的用户脚本开发者.
Can you add a feature to sync code from github on your website? like [greasyfork.org](https://greasyfork.org)
能否在你的网站上添加一个同步github代码的功能吗? 就像[greasyfork.org](https://greasyfork.org)

https://gloria.pub/task/5eff1911ab474400108be5ef

**Comment by BlackGlory** [comment]
新特性都得等到遥遥无期的v1.0版本, 此项目现阶段的代码基本上已经没有修改价值了(使用的语言LiveScript也停止更新2年了), 在v1.0里包括GloriaScript本身的写法都会有比较大的改动.

直接同步Github仓库的想法暂时没有, 同步Github Gist或者其他直接输出文本的URL是在计划之中的(因为我不能保证Gloria.Pub会持续运行下去), 所以Github仓库里的代码文件是有可能以Raw形式同步的.

**Comment by BlackGlory** [comment]
由于 #41 关闭.
