### ISSUE TITLE
通知会集中出现

### ISSUE THREAD

**Issue by Zeroto521** [BlackGlory/Gloria#3]
放置一段时间（锁屏，离开）后，再次打开电脑（浏览器）通知会集中出现。
嗯~让我防不胜防。_(:з」∠)_

截图
> ![image](https://user-images.githubusercontent.com/25895405/47255448-ec0f8d00-d4a3-11e8-8641-fcc5240d0de5.png)

**Comment by BlackGlory** [comment]
这是预期的行为呀, 你想要的是什么样的效果? 所有锁屏后的通知全部被忽略?

**Comment by Zeroto521** [comment]
不是有个 `弹出的通知需要手动关闭` 吗。
这么理解的话，那没勾选这个选项，一段时间后通知应该会自动消失的吧。

> ![image](https://user-images.githubusercontent.com/25895405/47264237-4876b900-d545-11e8-9087-041c281952ce.png)

**Comment by BlackGlory** [comment]
你的理解没错, 但是这个选项是以"弹出"为前提才有效的, 实际情况是Chrome在锁屏后就不会弹出通知了, 所有锁屏期间发出的通知会延迟到下一次解锁后再弹出, 这大概是为了避免人们错过重要通知而设计的.

**Comment by Zeroto521** [comment]
那这种情况何解呢？
这样用户体验很糟糕的。
_(:з」∠)_

**Comment by Zeroto521** [comment]
或者说有没有可能增加 “休眠” 机制

**Comment by BlackGlory** [comment]
我在1.0版本里准备了一些方案来让用户可以一次性清除时效性强(如果不及时看到就会失去意义)的通知和直接清除全部未显示的通知(转而进入单独的页面方便快速浏览), 不过这个版本可能要到年底才能准备好了.

**Comment by Zeroto521** [comment]
chrome 版本更新后，window 平台通知已经整合到了 window 通知管理了。

这或许意味着，可以通过 window 的通知管理对 Gloria 进行管理。

**Comment by BlackGlory** [comment]
去年我写了个UWP应用尝试过, 发现Windows 10的通知每次只能显示一个, 也就是说如果有大量通知是应付不了的. 另外还有一个问题就是默认的黑色主题显示通知很丑, 即将更新的19h1的明亮主题显示起来会好一些. 目前的计划是推出单独的通知应用以应付不同的操作系统而不依赖系统通知(不过用户也可以自主选择使用系统通知).

**Comment by BlackGlory** [comment]
由于 #41 关闭.
