### ISSUE TITLE
除了gloria-utils里面的cookie,还有其他库可以r/w本地数据吗

### ISSUE THREAD

**Issue by icanye** [BlackGlory/Gloria#30]
未来有对localStorage和indexedDB的支持吗

**Comment by BlackGlory** [comment]
不记得当时出于什么原因把cookie加进gloria-utils了, 脚本理念上是无状态的, 不鼓励直接访问cookies或其他本地数据, 未来也没有加入相关接口的打算.

**Comment by icanye** [comment]
> 因把cookie加进gloria-utils了, 脚本理念上是无状态的, 不鼓励直接访问cookies或其他

目前我想实现个功能是通过gloria脚本定时发送到pushplus或者serverchan这些第三方通知,我想记录近期已推送的数据,防止二次推送

我看到这个工具集里有cookie相关的库,但是这个储存空间还是比较小的,所以有什么其他方法可以实现吗,无需mq,kafka一类的服务端托管

**Comment by BlackGlory** [comment]
可以用Gloria的[Reducer特性](https://docs.gloria.pub/gao-ji-she-zhi/notification-reducer), 这个函数只会收到预备弹出的通知.
主要问题是设计时没有考虑到如何区分不同任务产生的通知.

**Comment by LightAPIs** [comment]
如果是同一任务的去重，直接在任务中给 `commit` 传递数组就好了，内部会处理，再在 Reducer 中给第三方服务发送 http 请求。
如果是多个任务里可能会出现相同的结果，目前的设计是没法直接处理；但是在 Reducer 函数里其实是可以使用 localStorage/indexedDB 的(**虽然我非常反对这样做**)，如果你确实有这种需求可能只能自己在 Rudecer 里去手动实现了。

**Comment by icanye** [comment]
> 如果是同一任务的去重，直接在任务中给 `commit` 传递数组就好了，内部会处理，再在 Reducer 中给第三方服务发送 http 请求。
> 如果是多个任务里可能会出现相同的结果，目前的设计是没法直接处理；但是在 Reducer 函数里其实是可以使用 localStorage/indexedDB 的(**虽然我非常反对这样做**)，如果你确实有这种需求可能只能自己在 Rudecer 里去手动实现了。

感谢分享,我需要的确实就是一个预过滤的功能
