### ISSUE TITLE
Github dashboard feed - Task don't work anymore

### ISSUE THREAD

**Issue by Slippy2k** [BlackGlory/Gloria#33]
Hello,
your Task
https://gloria.pub/task/57af71d4af1728000fddef65
for Github don't work anymore
Can you fix this please

**Comment by BlackGlory** [comment]
Sorry, I don't have time to do this.

**Comment by LightAPIs** [comment]
Do you want such a task [Github dashboard feed](https://gloria.pub/task/61b43317b93475001181e1b6).

**Comment by Slippy2k** [comment]
> Do you want such a task [Github dashboard feed](https://gloria.pub/task/61b43317b93475001181e1b6).

Thank you this works

**Comment by BlackGlory** [comment]
Closed due to #41.
