### ISSUE TITLE
为什么没有弹窗通知

### ISSUE THREAD

**Issue by 362227** [BlackGlory/Gloria#35]
推送正常，但不会有弹窗

**Comment by 362227** [comment]
换了edge可以了，但chrome为什么不行

**Comment by BlackGlory** [comment]
在Chrome还在Windows上使用自己的通知界面的时代, 通知有个禁止弹出通知的设置功能, 可以禁用特定扩展程序的通知, 很容易在弹出通知时误触, 可能是因为这个导致没有通知.
另一种更现代的原因可能是[这个](https://stackoverflow.com/a/69959668/5462167).

**Comment by 362227** [comment]
感谢，已解决
