### ISSUE TITLE
能否修改 user-agent

### ISSUE THREAD

**Issue by lqzhgood** [BlackGlory/Gloria#37]
有些监控页面是移动端的，所以 fetch 修改 ua 拿到页面数据，但是我修改后发现无效。
`
fetch(url,{
    headers:{
        'user-agent': 'Mobile'
    }
})
`

似乎是 Chrome 不支持修改 user-agent，https://bugs.chromium.org/p/chromium/issues/detail?id=571722
有办法绕过不？例如通过 node runtime ？

**Comment by BlackGlory** [comment]
修改是可能的, 但要通过扩展程序API才能实现, 见https://developer.chrome.com/docs/extensions/reference/webRequest/:
```
The following headers are currently **not provided** to the `onBeforeSendHeaders` event. This list is not guaranteed to be complete nor stable.

*   Authorization
*   Cache-Control
*   Connection
*   Content-Length
*   Host
*   If-Modified-Since
*   If-None-Match
*   If-Range
*   Partial-Data
*   Pragma
*   Proxy-Authorization
*   Proxy-Connection
*   Transfer-Encoding
```

现在的问题是, Gloria正在使用的Manifest V2 API正在被弃用, 而下一代Manifest V3 API并没有确定好如何允许运行用户脚本.
直到Manifest V3的相关API尘埃落定之前, 继续维护Gloria没有什么意义. 所以如果你想要相关功能, 只能自己修改Gloria的源代码.

受到Manifest V3目前糟糕的API设计理念的影响, 届时也许油猴脚本这样的扩展程序会继续得到支持, 而Gloria这样在后台运行的脚本有可能无法运行, 毕竟两者的用户数不在一个量级.

作为替代方案, 我确实打算开发一个Node运行时或Deno运行时, 但还没有开始, 可以肯定的是相关设计肯定会和现在的Gloria大有不同.
尤其是Deno, 不难从零开始创造一个具有Gloria 80%功能的程序, 因为像`fetch`这样的全局函数已经内置在Deno里.
只需要抓取数据, 生成通知, 去重通知, 然后将新通知转发给一个能够起到通知作用的程序就可以了, 比如这个模仿Chrome通知的客户端项目 https://github.com/UniversalNotification/unotifier-desktop.
