### ISSUE TITLE
[bug] Edge 浏览器无法后台触发 commit 通知~

### ISSUE THREAD

**Issue by lqzhgood** [BlackGlory/Gloria#38]
使用 Edge 浏览器，添加以下代码，并设置为1分钟， 打开 `background` 页的 F12 可以看到有定时执行，但是并不会弹出通知~

```js
commit({ message: "hhhhhh",  });
```

从前台的测试代码处执行会有通知

Edge版本 112.0.1722.58 (正式版本) (64 位)

**Comment by LightAPIs** [comment]
因为你这样写每次 `commit`  的内容都是一样的，不会有新内容，也就没有通知了。如果想测试你可以这样写：

```js
commit({
  id: Date.now().toString(),
  message: 'hhhhhh',
});
```
