### ISSUE TITLE
求写个instagram首页订阅面的

### ISSUE THREAD

**Issue by p1956** [BlackGlory/Gloria#4]
需要登录的那种。因为订阅太多用户，一个个添加太吃资源。要求会显示作者，视频也能有预览图，谢谢

**Comment by p1956** [comment]
另外希望弹窗提示能显示更多的标题，带图的标题就一行文字，导致信息量太少，要点进去看，不带图的有好几行，比较正常

**Comment by p1956** [comment]
youtube和推特的脚本都失效了
https://gloria.pub/task/57baade933fc01000f57ac90
https://gloria.pub/task/5820b34bb1f689000f0f457c

**Comment by BlackGlory** [comment]
由于新版本的任务代码格式与旧版本会有区别, 在下个版本发布之前不会更新任务代码了, 见谅.

p1956 <notifications@github.com> 于2018年11月27日周二 上午12:49写道：

**Comment by BlackGlory** [comment]
由于 #41 关闭.
