### ISSUE TITLE
测试任务代码的时候怎么中止啊

### ISSUE THREAD

**Issue by arpir** [BlackGlory/Gloria#40]
以这个任务为例 https://gloria.pub/task/64f38d0db7af1c0010ac0f73 代码还是有一些问题，但是测试的时候会一直弹出通知，试过 「清理所有 STAGES(一个用于缓存通知的内部组件)」、「清理所有 CACHES(一个用于缓存网络请求的内部组件）」也无济于事。

**Comment by BlackGlory** [comment]
测试时的弹出通知是不能中止的, 等所有通知弹出完就行了.
对于一些平台(例如Windows 10), 每次只能显示一个通知, 通知弹完会需要比较长的时间.

**Comment by arpir** [comment]
> 测试时的弹出通知是不能中止的, 等所有通知弹出完就行了. 对于一些平台(例如Windows 10), 每次只能显示一个通知, 通知弹完会需要比较长的时间.

嗯嗯，我也发现了，最终好像能通过关闭拓展来解决无限循环通知或通知太多一直提示的问题。
