### ISSUE TITLE
logo 附近有留白

### ISSUE THREAD

**Issue by Zeroto521** [BlackGlory/Gloria#5]
## 问题

logo 附近（上下左右）都有条线。

![image](https://user-images.githubusercontent.com/25895405/49692119-74014180-fb8d-11e8-819e-631bd19da522.png)

## 可能原因

这个问题可能跟自己最近更新到了 `71.0.3578.80`  有关。

因为不只是 Gloria 出现这种情况，其他插件通知也会如此，¯\_(ツ)_/¯

**Comment by BlackGlory** [comment]
是Chrome 71改变了界面, Chrome的通知经常会有细微的调整, 好在这次没搞出什么bug.

Zero <notifications@github.com> 于2018年12月9日周日 上午8:39写道：

**Comment by Zeroto521** [comment]
嗯~ Chrome 的锅，¯\_(ツ)_/¯
