### ISSUE TITLE
大佬能否写一个rarbg的关键词更新啊...

### ISSUE THREAD

**Issue by Noah1995** [BlackGlory/Gloria#6]
嘤嘤嘤...
最好可以支持多个词语单独探测...
https://rarbgprx.org/torrents.php

**Comment by BlackGlory** [comment]
我记得rarbg有Cloudflare的机器人检查, 应该是没法做.

**Comment by Noah1995** [comment]
好像是每天第一次会验证吧...
不是每次惹...
