### ISSUE TITLE
【功能】不知能否做到增加类似点击输入框快捷自动可以添加任务?

### ISSUE THREAD

**Issue by Noah1995** [BlackGlory/Gloria#7]
我想要一个不同网站自动一键匹配关键字的..
类似[SearchBar](https://chrome.google.com/webstore/detail/searchbar/fjefgkhmchopegjeicnblodnidbammed)和[Selection Search](https://chrome.google.com/webstore/detail/selection-search/gipnlpdeieaidmmeaichnddnmjmcakoe)

**Comment by Noah1995** [comment]
![【2019 05 26】【10∶34∶31】](https://user-images.githubusercontent.com/25548230/58376678-50e31680-7fa2-11e9-818d-dea178b8cf43.gif)

**Comment by BlackGlory** [comment]
下个版本的计划中有, 但下个版本什么时候做完还未可知...

**Comment by Noah1995** [comment]
> 下个版本的计划中有，但下个版本什么时候做完尚未可知...

![ezgif-6-822f3709ed93](https://user-images.githubusercontent.com/25548230/69481498-d7db5380-0e4c-11ea-96ce-8a2f1ff697ec.gif)
还有能增加类似Distill Web Monitor这样div自动选择吗?
这个只能显示文字不太完美...
https://chrome.google.com/webstore/detail/distill-web-monitor/inlikjemeeknofckkjolnjbpehgadgge

**Comment by BlackGlory** [comment]
@Noah1995 不能.

从现有的网页里自动提取出符合语义的范式(不会因为页面在实现上的细微差别而失效)是很困难的, 这一点我最近在很多网页中实验过了. 当我们使用这种简易的数据提取工具时, 很难保证相应的选择器在网页的变动中有效, 既然如此, 为什么不直接自己看网页的源代码?

如果仅仅是为了不了解JavaScript和HTML的新手提供这项功能, 似乎也没有多大用处, 因为Gloria需要从数据中生成出通知. 如果用户不依赖于这种功能就无法编写出Gloria脚本, 那么实际上他也很可能不能应付网页将来变化的情况. 也就是说一个用户可能会遇上这种情况: 他在短时间内依赖于提取工具生成的脚本来提供某个网站的通知, 然后有一天这个网站进行了大刀阔斧的改版, 新版网站不再能够通过提取工具自动生成通知(现代网站的进化过程大抵如此, Youtube就是一个很好的例子), 于是用户就因为这个原因, 失去了一个过去依赖着的可能的重要功能. 这带来的最终用户体验非常糟糕(当前版本的Gloria无法提示用户脚本失效的情况, 所以更加糟糕), 既然如此, 那么不如一开始就不要提供这种傻瓜式的辅助方法.

考虑到Gloria不是一个一次性数据提取工具(这种工具只需要保证当时框选出需要的数据能够被提取), 这种功能不太可能被实现, 即使实现也是形式大于意义. 比如XPath和CSS选择器的提取在浏览器自带的开发者工具里就内置提供了, 但是却没有实用价值——即便在仅仅是为了辅助编写脚本的情况下, 人们也不应该使用这项功能, 因为并不靠谱.

**Comment by BlackGlory** [comment]
由于 #41 关闭.
不过现在的技术条件有点不同了, 也许SOTA水准的LLM能满足这项需求.
